### PR TITLE
fixing svg & demo

### PR DESCRIPTION
**Pull request by haiderghaleb**

### CODE REVIEW

**Comment by victorsosa** [comment]
Thank you, I will check this out and merge asap

**Comment by haiderghaleb** [comment]
@victorsosa cool, let's do it asap so we can use the normal adding plugin also I will work on the iOS fix but in the next days

**Comment by victorsosa** [comment]
@haiderghaleb please fix the version number so I can merge this asap

**Comment by haiderghaleb** [comment]
Done, change package version to 1.1.4

**Comment by victorsosa** [comment]
@haiderghaleb please fix the version number on the commented files too, please

**Comment by haiderghaleb** [comment]
@victorsosa can u tell me in which filename? I changed the package.json to 1.1.4, do you want me to change it to 1.1.5?

**Comment by victorsosa** [comment]
@haiderghaleb no, please check code comments on package.json

**Comment by haiderghaleb** [comment]
@victorsosa pushed all the changes

**Comment by haiderghaleb** [comment]
@victorsosa let me know if you need any changes from my side

**Comment by victorsosa** [comment]
Thank, awesome work

**Pull request merged**
